In [1]:
import numpy as np
import matplotlib.pyplot as plt
# from mpl_toolkits.mplot3d import Axes3D

from layers import DenseLayer
from cnn import NeuralNetwork

X = np.reshape([[0, 0], [0, 1], [1, 0], [1, 1]], (4, 2, 1))
Y = np.reshape([[0], [1], [1], [0]], (4, 1, 1))

layers = [
    DenseLayer(2, 3, activation="tanh"),
    DenseLayer(3, 1, activation="tanh"),
]

# train
model = NuralNetwork()
model.layers = layers
model.train(X, Y, epochs=1000, learning_rate=0.1, batch_size=1)

# decision boundary plot
points = []
for x in np.linspace(0, 1, 20):
    for y in np.linspace(0, 1, 20):
        z = model.predict(np.reshape([[x], [y]], (2, 1)))
        points.append([x, y, z[0,0]])

points = np.array(points)

# fig = plt.figure()
# ax = fig.add_subplot(111, projection="3d")
# ax.scatter(points[:, 0], points[:, 1], points[:, 2], c=points[:, 2], cmap="winter")
# plt.show()

ImportError: cannot import name 'NuralNetwork' from 'cnn' (/Users/michalhoffmann/Desktop/studia/mpum/MPUM_main/code/cnn.py)

In [ ]:
from keras.datasets import mnist
from keras import utils

In [ ]:
%load_ext autoreload
%autoreload 2

import numpy as np

from layers import ConvLayer, FlattenLayer, DenseLayer
from losses import *
from cnn import NeuralNetwork

def preprocess_data(x, y, limit):
    zero_index = np.where(y == 0)[0][:limit]
    one_index = np.where(y == 1)[0][:limit]
    all_indices = np.hstack((zero_index, one_index))
    all_indices = np.random.permutation(all_indices)
    x, y = x[all_indices], y[all_indices]
    x = x.reshape(len(x), 1, 28, 28)
    x = x.astype("float32") / 255
    y = utils.to_categorical(y)
    y = y.reshape(len(y), 2, 1)
    return x, y

# load MNIST from server, limit to 100 images per class since we're not training on GPU
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, y_train = preprocess_data(x_train, y_train, 100)
x_test, y_test = preprocess_data(x_test, y_test, 100)

# neural network
layers = [
    ConvLayer(5, 3, (1, 28, 28), activation="sigmoid"),
    FlattenLayer((5,26,26)),
    DenseLayer(5 * 26 * 26, 100, activation='sigmoid'),
    DenseLayer(100, 2, activation="sigmoid"),
]

model = NeuralNetwork(loss='binary_crossentropy')
model.layers = layers
# train
model.train(
    x_train,
    y_train,
    epochs=10,
    learning_rate=0.1,
    batch_size=1
)

# test
# for x, y in zip(x_test, y_test):
#     output = model.predict(x)
#     print(f"pred: {np.argmax(output)}, true: {np.argmax(y)}")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
[[0.7409632 ]
 [0.61925631]] [[1.]
 [0.]]
loss 0.6327165915219699
[[0.32212195]
 [0.91534618]] [[0.]
 [1.]]
loss 0.8713370001643759
[[0.59860566]
 [0.29551479]] [[0.]
 [1.]]
loss 1.9372606754835309
[[0.14486327]
 [0.99151369]] [[0.]
 [1.]]
loss 2.0197688892011616
[[0.00325367]
 [0.99168092]] [[0.]
 [1.]]
loss 2.0255753132676806
[[0.03867248]
 [0.23085604]] [[1.]
 [0.]]
loss 3.783127455757927
[[0.96692534]
 [0.77699188]] [[0.]
 [1.]]
loss 5.613784124343411
[[0.11319982]
 [0.8277888 ]] [[0.]
 [1.]]
loss 5.768350537901268
[[0.09612461]
 [0.39703286]] [[1.]
 [0.]]
loss 7.192351790297935
[[0.9115023 ]
 [0.16163261]] [[1.]
 [0.]]
loss 7.326831800207389
[[0.87743849]
 [0.57770136]] [[0.]
 [1.]]
loss 8.65075205477785
[[0.51444178]
 [0.44473846]] [[1.]
 [0.]]
loss 9.277246516055945
[[0.82594344]
 [0.04760823]] [[1.]
 [0.]]
loss 9.397250410847636
[[0.96720749]
 [0.0796833 ]] [[0.]
 [1.]]
loss 12.3708756524342